#  __  __ _            __  __             _
# |  \/  (_)          |  \/  |           (_)
# | \  / |_ _ __   ___| \  / | __ _ _ __  _  __ _
# | |\/| | | '_ \ / _ \ |\/| |/ _` | '_ \| |/ _` |
# | |  | | | | | |  __/ |  | | (_| | | | | | (_| |
# |_|  |_|_|_| |_|\___|_|  |_|\__,_|_| |_|_|\__,_|
#
# Author: MineManiaUK Staff

# Chat Enabled
# Only users with permission chat.bypass.disable can chat if this is false
chat-enabled: true

# Clear Chat Lines
clear-chat-lines: 100

# Discord alert webhook URL
webhook-enabled:
webhook-url:

database:
  enabled: true
  litebans:
    url: ""
    user: ""
    password: ""

  premium-vanish:
    url: ""
    user: ""
    password: ""

# In order of priority.
# The first one will have the most priority.
format:
  # This will have the permissions chat.default
  default:
    prefix: ""
    postfix: ""